// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pexkiuefywrzffcopsgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBleGtpdWVmeXdyemZmY29wc2dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM3NjQ1NTYsImV4cCI6MjA4OTM0MDU1Nn0.83tjWeaQpY5KbxJ4Y3lgNC7Mjn8V9pqbZbXFfpEscbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});