// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from "@supabase/supabase-js";
import { getCredentials } from "@/lib/supabase-credentials";

// Placeholder URL used only to create a non-crashing dummy client
const PLACEHOLDER_URL = "https://placeholder.supabase.co";
const PLACEHOLDER_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder";

type AppDatabase = {
  public: {
    Tables: {
      news: {
        Row: { id: string; title: string; content: string; type: string; created_at: string };
        Insert: { id?: string; title: string; content: string; type: string; created_at?: string };
        Update: { id?: string; title?: string; content?: string; type?: string; created_at?: string };
      };
      completed: {
        Row: { id: string; title: string; content: string; type: string; created_at: string };
        Insert: { id?: string; title: string; content: string; type: string; created_at?: string };
        Update: { id?: string; title?: string; content?: string; type?: string; created_at?: string };
      };
      webhooks: {
        Row: { id: string; name: string; webhook_url: string; created_at: string };
        Insert: { id?: string; name: string; webhook_url: string; created_at?: string };
        Update: { id?: string; name?: string; webhook_url?: string; created_at?: string };
      };
      chat_options: {
        Row: { id: string; chat_text: string; chat_query: string; created_at: string };
        Insert: { id?: string; chat_text: string; chat_query: string; created_at?: string };
        Update: { id?: string; chat_text?: string; chat_query?: string; created_at?: string };
      };
    };
    Views: Record<string, never>;
    Functions: {
      delete_news_item: {
        Args: { item_id: string };
        Returns: void;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

function createSupabaseClient(): SupabaseClient<AppDatabase> {
  const creds = getCredentials();
  const url = creds.supabaseUrl || PLACEHOLDER_URL;
  const key = creds.supabaseKey || PLACEHOLDER_KEY;
  return createClient<AppDatabase>(url, key);
}

export let supabase = createSupabaseClient();

// Listen for credential changes and reinitialize
if (typeof window !== 'undefined') {
  window.addEventListener('supabase-credentials-changed', () => {
    supabase = createSupabaseClient();
  });
}
